ALTER TABLE users
ADD COLUMN IF NOT EXISTS locked BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS banned BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS ban_reason TEXT;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS locked_at TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS banned_at TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_users_locked ON users(locked);
CREATE INDEX IF NOT EXISTS idx_users_banned ON users(banned);
